-record(user_udp,{uid=0,ip="",port=0,data=0}).
-record(user_net,{id=0,name="",sex=1,photo="",sid=0,coin=0,scene=0,game=0,matching=0,skin=0,online=false}).
-record(scene,{id=0,hid=0,owner=0,alive=0,game=0,players=[]}).